README.md
signed-off-by: Nitish Kulkarni <nitish.kulkarni3@ibm.com>
=> chore: add device count API, apispeclint errors fix and binary mode separation

README.md
updated readme on private end points.
**Fixes:** [5450](https://github.ibm.com/Notification-Hub/planning/issues/5450)
More explanation on private end point was missing.
Given more details on private end point configuration
=> chore: updated readme for private end point

CHANGELOG.md, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, package-lock.json, package.json, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
**Fixes:** https://github.ibm.com/notification-hub/planning/issues/5151
https://github.ibm.com/Notification-Hub/planning/issues/5638
opt in for email in not present.
added with optin for email as EN comply with regulatory standards
=> chore: email opt in changes

examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js
Signed-off-by: Nitsh Kulkarni <nitish.kulkarni3@ibm.com>
PR includes example updates and test cases for push destinations.
Examples were not updated for push destinations
included examples and test cases for push destinations
=> chore: update examples and test cases

event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
SMS opt in changes
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/5269)
sms opt in was not there
added sms opt in feature as per the standards
=> chore: sms opt in changes

README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/6034)
Pagerduty destination support is not there
added Pagerduty destination support
=> chore: add Pagerduty destination

.secrets.baseline, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js
Fixed for false positive audit checks and updated accordingly.
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/6684)
dummy values are used as secrets but detected as secrets in audit
removed dummy values and considered as false positive.
=> chore: fixed false positive audit checks

.secrets.baseline, .travis.yml, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, package-lock.json, package.json, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
PR includes changes of support for new destination service now.
**Fixes:** <! -- [link to issue](https://github.ibm.com/Notification-Hub/planning/issues/6640) -->
no support of service now destination
added support for service now destination, 
For vulnarability fixes updated node core sdk to 4.0.3 because of which the minimum required node version is 14.
=> chore: add service now destination support

.secrets.baseline
false positive alert for SDK
updated secrets.baseline file
=> chore: audit fix for false positve

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, package-lock.json, test/integration/event-notifications.v1.test.js
PR includes changes for support of FCM HTTP V1 support in EN.
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/6928)
Currently has only support for HTTP legacy API.
include support of FCM HTTP V1 support.
=> chore: add FCM V1 destination support

.secrets.baseline, event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js
Includes support for code engine as a destination.
**Fixes:** (https://github.ibm.com/Notification-Hub/planning/issues/7627)
Code engine destination support was not there
added support for code engine as destination
=> chore: add code engine destination support

.secrets.baseline, event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js
Inlcludes changes for COS destination support
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/7746)
there was no support for adding COS as a destination
Added support for adding COS as new destination
=> chore: adds COS destination support

.secrets.baseline, event-notifications/v1.ts, examples/event-notifications.v1.test.js, package-lock.json, package.json, test/integration/event-notifications.v1.test.js
**Fixes:** <! --[ link to issue ](https://github.ibm.com/notification-hub/planning/issues/8314)-->
* No support of Huawei destination
* added support for Huawei destination
=> chore: huawei destination support

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, package-lock.json, package.json, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
Signed-off-by: nitish <nitish.kulkarni3@ibm.com>
adds support for adding custom domain email as a destination
**Fixes:** https://github.ibm.com/notification-hub/planning/issues/9287
do not have support for custom domain email
adds support for custom domain email destination
=> chore: adds custom domain email support

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
Adds support for templates.
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/9860)
no support of templates
adds support for templates
=> chore: adds templates support

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
notification payload changes for custom email- bypass subscription
**Fixes:** <! -- [ink to issue](https://github.ibm.com/Notification-Hub/planning/issues/10427) -->
bypass subscription for custom email is not present
notification payload changes for custom email- bypass subscription
=> chore: custom email notification payload update

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
PR includes changes of test http destination connection
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/10123)
currently test API for http destination connection was not there
includes test API for http destination connection
=> chore: add test http destination support

.travis.yml, package-lock.json, package.json
build issue fix
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/10746)
build is failing with npm version
updated npm to npm@9
=> chore: build issue fix

package-lock.json
updated packages for vulnerability fix
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/11930)
packages are not up to date
updated packages
=> chore: vulnerability fix

package-lock.json, package.json
fix for build failure on samantic release
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/13028
https://github.ibm.com/Notification-Hub/planning/issues/13037
https://github.ibm.com/Notification-Hub/planning/issues/13639
semantic release version was updated by mistake hence minimum required node version is 20. 
in order to give release on and support node 18 reverted back the changes of semantic release package update
=> chore: build fix

package-lock.json
updated packages for vulnerability fix
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/14065
vulnerability detected in micromatch-4.0.5.tgz and braces-3.0.2.tgz packages
updated packages for vulnerability fix
=> chore: pakage update for vulnerability fix

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
https://github.ibm.com/Notification-Hub/planning/issues/14492
MMS support was not available, CF destination was supported from SDK
MMS has been enabled , CF destination support has been deprecated from SDK
=> chore: mms support and cf deprecation 

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
https://github.ibm.com/Notification-Hub/planning/issues/15030
SMTP Allowed IP Update is supported, Metrics feature is not part of SDK
SMTP allowed IP will be unsupported, Metrics feature has been introduced
=> SMTP allowed IP Update unsupported, Metrics Feature enabled

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, package-lock.json, test/integration/event-notifications.v1.test.js, test/unit/event-notifications.v1.test.js
**Fixes: https://github.ibm.com/Notification-Hub/planning/issues/14221
slack direct message was not supported
slack direct message is supported now.
Slack destination creation/update operation -  interface DestinationConfigOneOfSlackDirectMessageDestinationConfig is added with one more attribute "type" to define the destination type. Supported types are "incoming_webhook" and "direct_message".
=> chore: support slack DM

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, test/integration/event-notifications.v1.test.js
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/15830
support of webhook template was not there
provided support for webhook template
=> chore: webhook template support

.secrets.baseline, README.md, event-notifications/v1.ts
https://github.ibm.com/Notification-Hub/planning/issues/16136
was having support for IBM cloud functions
Due to deprecation removing support of cloud functions
=> chore: removed cloud functions support 

.secrets.baseline, README.md, event-notifications/v1.ts, examples/event-notifications.v1.test.js, package-lock.json, package.json, test/integration/event-notifications.v1.test.js
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/16809
there is no support for pagerduty templates
support for pagerduty template
=> chore: pagerduty template support

.secrets.baseline, README.md, event-notifications/v1.ts, test/integration/event-notifications.v1.test.js
Support for code engine templates (Application and Jobs)
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/18346
=> feat: support for code engine templates
